-- Fix e2e test user passwords to BCrypt hash for 'Test@1234'
-- Hash generated by Spring Boot BCryptPasswordEncoder(10)
UPDATE users 
SET password_hash = '$2a$10$maNiaEtOZzJupIB9rVzxf.RNmNNfu3P0gxUeewM/tio5WVYrcWzXO'
WHERE email LIKE 'e2e_%@test.com';

SELECT email, LEFT(password_hash, 7) || '...' as hash_prefix FROM users WHERE email LIKE 'e2e_%@test.com';
